/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { jsPDF } from "jspdf";
import { Match, InningsState, BatsmanStats, BowlerStats, CommitteeMember } from "../types";
import { formatOvers, calculateStrikeRate, calculateEconomyRate, calculatePointsTable } from "../utils";

/**
 * Generates and downloads a beautifully styled, SINGLE PAGE PDF Match Report.
 * Both innings are laid out side-by-side (2 columns) to fit everything on one page.
 */
export function downloadMatchReportPDF(
  match: Match,
  allMatches: Match[] = [],
  committeeMembers: CommitteeMember[] = []
) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 10;
  const contentWidth = pageWidth - 2 * margin; // 190mm
  const bpo = match.ballsPerOver || 6;

  const GREEN: [number, number, number] = [4, 120, 87];
  const BLUE: [number, number, number] = [29, 78, 216];
  const DARK: [number, number, number] = [15, 23, 42];
  const MUTED: [number, number, number] = [100, 116, 139];

  // ---------- Helpers ----------
  const drawHorizontalLine = (y: number, colorRGB: number[] = [226, 232, 240], thickness = 0.15) => {
    doc.setDrawColor(colorRGB[0], colorRGB[1], colorRGB[2]);
    doc.setLineWidth(thickness);
    doc.line(margin, y, margin + contentWidth, y);
  };

  // Truncate text with ellipsis so it never overflows a column
  const truncate = (text: string, maxWidth: number, fontSize: number) => {
    doc.setFontSize(fontSize);
    if (doc.getTextWidth(text) <= maxWidth) return text;
    let out = text;
    while (out.length > 1 && doc.getTextWidth(out + "…") > maxWidth) {
      out = out.slice(0, -1);
    }
    return out + "…";
  };

  // ---------- Header Banner (compact) ----------
  doc.setFillColor(7, 36, 16);
  doc.rect(0, 0, pageWidth, 22, "F");
  doc.setFillColor(234, 179, 8);
  doc.rect(0, 21.5, pageWidth, 0.8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("PATHTHAWA SUPER LEAGUE 2026", margin, 8);

  doc.setFontSize(13);
  doc.setTextColor(234, 179, 8);
  doc.text("OFFICIAL MATCH REPORT", margin, 15);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(6.5);
  doc.setTextColor(167, 243, 208);
  doc.text("Generated by Arsaam Admin Scoring Center", margin, 19.5);

  const hasStandingsPage = allMatches && allMatches.length > 0;
  const totalPages = hasStandingsPage ? 2 : 1;

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(`Page 1 of ${totalPages}`, pageWidth - margin, 10, { align: "right" });

  // ---------- Footer (compact) ----------
  const drawFooter = (pageNum: number) => {
    const footerY = pageHeight - 8;
    drawHorizontalLine(footerY - 3, [200, 220, 200], 0.25);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "This is an official computer-generated Match Report from PATHTHAWA SUPER LEAGUE 2026 Live Scoring.",
      margin,
      footerY
    );
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, footerY, { align: "right" });
  };
  drawFooter(1);

  let currentY = 27;

  // ---------- Match Summary Card ----------
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.rect(margin, currentY, contentWidth, 26, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`${match.teamA.toUpperCase()} vs ${match.teamB.toUpperCase()}`, margin + 4, currentY + 5.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${match.date}   |   ${match.venue}   |   Max ${match.maxOvers} Overs`, margin + 4, currentY + 10);

  const tossText = match.tossWinner
    ? `${match.tossWinner} won the toss and elected to ${match.tossDecision === "Bat" ? "Bat first" : "Bowl first"}`
    : "Toss details not recorded";
  doc.text(tossText, margin + 4, currentY + 14);

  // Result banner
  doc.setFillColor(254, 243, 199);
  doc.rect(margin + 3, currentY + 16.5, contentWidth - 6, 8.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(146, 64, 14);
  const resultStr = match.resultMessage || "Match upcoming or in progress";
  let momInline = "";
  if (match.manOfTheMatch) momInline = `   |   Man of the Match: ${match.manOfTheMatch}`;
  doc.text(`RESULT: ${resultStr}${momInline}`, margin + 6, currentY + 21.7);

  currentY += 30;

  // ---------- Two-column innings scorecards ----------
  const colGap = 4;
  const colWidth = (contentWidth - colGap) / 2;
  const col1X = margin;
  const col2X = margin + colWidth + colGap;

  const renderInningsColumn = (
    innings: InningsState | undefined,
    fallbackTeamName: string,
    x: number,
    startY: number,
    label: string,
    themeColor: [number, number, number],
    headerFill: number[]
  ): number => {
    let y = startY;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.text(`${label}: ${innings ? innings.battingTeam : fallbackTeamName}`, x, y);

    if (!innings) {
      y += 6;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text("Innings not started yet.", x + 2, y);
      return y + 4;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    const scoreStr = `${innings.runs}/${innings.wickets} (${formatOvers(innings.balls, bpo)} Ov)`;
    doc.text(scoreStr, x + colWidth, y, { align: "right" });
    y += 3;

    // Column offsets (relative widths tuned for colWidth ~ 93mm)
    const nameW = colWidth - 34; // leaves ~34mm for R/B/4/6/SR
    const rX = x + colWidth - 28;
    const bX = x + colWidth - 20;
    const fourX = x + colWidth - 13;
    const sixX = x + colWidth - 6;
    const srX = x + colWidth;

    // Batting header
    doc.setFillColor(headerFill[0], headerFill[1], headerFill[2]);
    doc.rect(x, y, colWidth, 4.2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.3);
    doc.setTextColor(71, 85, 105);
    doc.text("BATSMAN", x + 1.5, y + 3);
    doc.text("R", rX, y + 3, { align: "right" });
    doc.text("B", bX, y + 3, { align: "right" });
    doc.text("4s", fourX, y + 3, { align: "right" });
    doc.text("6s", sixX, y + 3, { align: "right" });
    doc.text("SR", srX, y + 3, { align: "right" });
    y += 4.2;

    innings.batsmen.forEach((batsman: BatsmanStats) => {
      let statusStr = "Not Out";
      if (batsman.isOut) {
        statusStr = batsman.dismissalType || "Out";
        if (batsman.dismissedBy) statusStr += ` b ${batsman.dismissedBy}`;
      }
      const nameLine = truncate(`${batsman.name}`, nameW, 6.8);
      const statusLine = truncate(statusStr, nameW, 5.8);

      doc.setFont("helvetica", batsman.isOut ? "normal" : "bold");
      doc.setFontSize(6.8);
      doc.setTextColor(15, 23, 42);
      doc.text(nameLine, x + 1.5, y + 3);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.text(`${batsman.runs}`, rX, y + 3, { align: "right" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      doc.text(`${batsman.balls}`, bX, y + 3, { align: "right" });
      doc.text(`${batsman.fours}`, fourX, y + 3, { align: "right" });
      doc.text(`${batsman.sixes}`, sixX, y + 3, { align: "right" });
      doc.text(calculateStrikeRate(batsman.runs, batsman.balls), srX, y + 3, { align: "right" });

      doc.setFont("helvetica", "italic");
      doc.setFontSize(5.6);
      doc.setTextColor(100, 116, 139);
      doc.text(statusLine, x + 1.5, y + 6);

      y += 7.2;
      drawHorizontalLine(y, headerFill, 0.1);
    });

    // Extras
    y += 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.3);
    doc.setTextColor(71, 85, 105);
    const extrasStr = `Extras: W${innings.wides || 0} NB${innings.noBalls || 0} B${innings.byes || 0} LB${innings.legByes || 0}`;
    doc.text(extrasStr, x + 1.5, y + 2.5);
    y += 6;

    // Bowling header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.text("Bowling", x, y);
    y += 2.5;

    doc.setFillColor(headerFill[0], headerFill[1], headerFill[2]);
    doc.rect(x, y, colWidth, 4.2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.3);
    doc.setTextColor(71, 85, 105);

    const bowlerNameW = colWidth - 45;
    const oX = x + colWidth - 38;
    const mX = x + colWidth - 27;
    const rConcX = x + colWidth - 18;
    const wX = x + colWidth - 8;
    const econX = x + colWidth;

    doc.text("BOWLER", x + 1.5, y + 3);
    doc.text("O", oX, y + 3, { align: "right" });
    doc.text("M", mX, y + 3, { align: "right" });
    doc.text("R", rConcX, y + 3, { align: "right" });
    doc.text("W", wX, y + 3, { align: "right" });
    doc.text("Econ", econX, y + 3, { align: "right" });
    y += 4.2;

    innings.bowlers.forEach((bowler: BowlerStats) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.8);
      doc.setTextColor(15, 23, 42);
      doc.text(truncate(bowler.name, bowlerNameW, 6.8), x + 1.5, y + 3);
      doc.text(formatOvers(bowler.ballsBowled, bpo), oX, y + 3, { align: "right" });
      doc.text(`${bowler.maidens}`, mX, y + 3, { align: "right" });
      doc.text(`${bowler.runsConceded}`, rConcX, y + 3, { align: "right" });
      doc.setFont("helvetica", "bold");
      doc.text(`${bowler.wickets}`, wX, y + 3, { align: "right" });
      doc.setFont("helvetica", "normal");
      doc.text(calculateEconomyRate(bowler.runsConceded, bowler.ballsBowled, bpo), econX, y + 3, { align: "right" });
      y += 4.6;
      drawHorizontalLine(y, headerFill, 0.1);
    });

    return y;
  };

  const endY1 = renderInningsColumn(
    match.innings1,
    match.teamA,
    col1X,
    currentY,
    "1st Innings",
    GREEN,
    [241, 245, 249]
  );
  const endY2 = renderInningsColumn(
    match.innings2,
    match.teamB,
    col2X,
    currentY,
    "2nd Innings",
    BLUE,
    [239, 246, 255]
  );

  currentY = Math.max(endY1, endY2) + 3;

  // ---------- Fall of Wickets (compact, combined) ----------
  const fowLines: string[] = [];
  if (match.innings1?.fallOfWickets?.length) {
    fowLines.push(
      `${match.innings1.battingTeam}: ` +
        match.innings1.fallOfWickets.map((f) => `${f.wicketNumber}-${f.score} (${f.batsmanName})`).join(", ")
    );
  }
  if (match.innings2?.fallOfWickets?.length) {
    fowLines.push(
      `${match.innings2.battingTeam}: ` +
        match.innings2.fallOfWickets.map((f) => `${f.wicketNumber}-${f.score} (${f.batsmanName})`).join(", ")
    );
  }
  if (fowLines.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(71, 85, 105);
    doc.text("Fall of Wickets", margin, currentY);
    currentY += 3;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.3);
    doc.setTextColor(100, 116, 139);
    fowLines.forEach((line) => {
      const wrapped = doc.splitTextToSize(line, contentWidth);
      doc.text(wrapped, margin, currentY);
      currentY += wrapped.length * 3 + 1.5;
    });
  }

  // ---------- Captains + Signature (fixed near bottom) ----------
  const sigY = pageHeight - 20;
  const captainsY = sigY - 16;

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.2);
  doc.line(margin, captainsY, margin + contentWidth, captainsY);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(15, 23, 42);
  doc.text("TEAM CAPTAINS", margin, captainsY + 3.5);

  const drawCaptainPlaceholder = (x: number, y: number, w: number, h: number, nameStr: string) => {
    doc.setFillColor(30, 64, 175);
    doc.roundedRect(x, y, w, h, 1.5, 1.5, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    const initial = nameStr.trim().charAt(0).toUpperCase() || "C";
    doc.text(initial, x + w / 2, y + h / 2 + 2.8, { align: "center" });
  };

  const teamACard = committeeMembers.find(
    (m) =>
      m.isOwner === true &&
      (m.role.toLowerCase().includes(match.teamA.toLowerCase()) ||
        match.teamA.toLowerCase().includes(m.role.replace(/^Owner,\s*/i, "").toLowerCase()))
  );
  const teamBCard = committeeMembers.find(
    (m) =>
      m.isOwner === true &&
      (m.role.toLowerCase().includes(match.teamB.toLowerCase()) ||
        match.teamB.toLowerCase().includes(m.role.replace(/^Owner,\s*/i, "").toLowerCase()))
  );

  const photoSize = 9;

  const capAName = teamACard?.captainName || "Not Assigned";
  const capAPhoto = teamACard?.captainPhotoUrl;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`${match.teamA} Captain: ${capAName}`, margin + 3, captainsY + 8);
  const photoAX = margin + 62;
  const photoAY = captainsY + 3;
  if (capAPhoto && capAPhoto.startsWith("data:image/") && capAPhoto.includes(";base64,")) {
    try {
      const format = capAPhoto.split(";")[0].split("/")[1].split("+")[0].toUpperCase();
      doc.addImage(capAPhoto, format === "JPEG" ? "JPEG" : "PNG", photoAX, photoAY, photoSize, photoSize);
    } catch (e) {
      console.error(e);
      drawCaptainPlaceholder(photoAX, photoAY, photoSize, photoSize, capAName);
    }
  } else {
    drawCaptainPlaceholder(photoAX, photoAY, photoSize, photoSize, capAName);
  }

  const capBName = teamBCard?.captainName || "Not Assigned";
  const capBPhoto = teamBCard?.captainPhotoUrl;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(`${match.teamB} Captain: ${capBName}`, margin + 100, captainsY + 8);
  const photoBX = margin + 160;
  const photoBY = captainsY + 3;
  if (capBPhoto && capBPhoto.startsWith("data:image/") && capBPhoto.includes(";base64,")) {
    try {
      const format = capBPhoto.split(";")[0].split("/")[1].split("+")[0].toUpperCase();
      doc.addImage(capBPhoto, format === "JPEG" ? "JPEG" : "PNG", photoBX, photoBY, photoSize, photoSize);
    } catch (e) {
      console.error(e);
      drawCaptainPlaceholder(photoBX, photoBY, photoSize, photoSize, capBName);
    }
  } else {
    drawCaptainPlaceholder(photoBX, photoBY, photoSize, photoSize, capBName);
  }

  // Signature lines
  doc.setDrawColor(220, 220, 220);
  doc.line(margin + 5, sigY, margin + 55, sigY);
  doc.line(pageWidth - margin - 55, sigY, pageWidth - margin - 5, sigY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Authorized Tournament Scorer", margin + 30, sigY + 3.5, { align: "center" });
  doc.text("Chief Tournament Director", pageWidth - margin - 30, sigY + 3.5, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(7, 36, 16);
  doc.text("ARSAAM", margin + 30, sigY - 1.5, { align: "center" });
  doc.text("ISMAN SCORING PANEL", pageWidth - margin - 30, sigY - 1.5, { align: "center" });

  // ---------- Page 2: Tournament Standings & NRR (only if match history available) ----------
  if (hasStandingsPage) {
    doc.addPage();

    // Header banner (page 2)
    doc.setFillColor(7, 36, 16);
    doc.rect(0, 0, pageWidth, 22, "F");
    doc.setFillColor(234, 179, 8);
    doc.rect(0, 21.5, pageWidth, 0.8, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("PATHTHAWA SUPER LEAGUE 2026", margin, 8);
    doc.setFontSize(13);
    doc.setTextColor(234, 179, 8);
    doc.text("OFFICIAL MATCH REPORT", margin, 15);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(6.5);
    doc.setTextColor(167, 243, 208);
    doc.text("Generated by Arsaam Admin Scoring Center", margin, 19.5);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`Page 2 of ${totalPages}`, pageWidth - margin, 10, { align: "right" });

    let standingsY = 30;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(7, 36, 16);
    doc.text("Tournament Standings & Net Run Rates (NRR)", margin, standingsY);
    standingsY += 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text("Latest updated standings including Net Run Rate (NRR) for all matches.", margin, standingsY + 2);
    standingsY += 8;

    doc.setFillColor(7, 36, 16);
    doc.rect(margin, standingsY, contentWidth, 7, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("POS", margin + 5, standingsY + 4.8, { align: "center" });
    doc.text("TEAM", margin + 10, standingsY + 4.8);
    doc.text("P", margin + 65, standingsY + 4.8, { align: "center" });
    doc.text("W", margin + 73, standingsY + 4.8, { align: "center" });
    doc.text("L", margin + 81, standingsY + 4.8, { align: "center" });
    doc.text("T/D", margin + 89, standingsY + 4.8, { align: "center" });
    doc.text("FOR (Runs/Overs)", margin + 112, standingsY + 4.8, { align: "center" });
    doc.text("AGAINST (Runs/Overs)", margin + 140, standingsY + 4.8, { align: "center" });
    doc.text("PTS", margin + 160, standingsY + 4.8, { align: "center" });
    doc.text("NRR", margin + 180, standingsY + 4.8, { align: "right" });

    standingsY += 7;

    const pointsTable = calculatePointsTable(allMatches);

    pointsTable.forEach((team, idx) => {
      doc.setFillColor(idx % 2 === 0 ? 248 : 241, idx % 2 === 0 ? 250 : 245, idx % 2 === 0 ? 252 : 249);
      doc.rect(margin, standingsY, contentWidth, 7.5, "F");

      const isCurrentTeam = team.teamName === match.teamA || team.teamName === match.teamB;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.8);
      doc.setTextColor(isCurrentTeam ? 4 : 15, isCurrentTeam ? 120 : 23, isCurrentTeam ? 87 : 42);
      doc.text(`${idx + 1}`, margin + 5, standingsY + 5, { align: "center" });
      doc.text(team.teamName, margin + 10, standingsY + 5);

      doc.setFont("helvetica", "normal");
      doc.text(`${team.played}`, margin + 65, standingsY + 5, { align: "center" });
      doc.text(`${team.won}`, margin + 73, standingsY + 5, { align: "center" });
      doc.text(`${team.lost}`, margin + 81, standingsY + 5, { align: "center" });
      doc.text(`${team.tied}`, margin + 89, standingsY + 5, { align: "center" });

      const forStr = `${team.runsScored}/${team.wicketsLost ?? 0} (${team.oversFaced.toFixed(1)})`;
      const agnstStr = `${team.runsConceded}/${team.wicketsTaken ?? 0} (${team.oversBowled.toFixed(1)})`;
      doc.text(forStr, margin + 112, standingsY + 5, { align: "center" });
      doc.text(agnstStr, margin + 140, standingsY + 5, { align: "center" });

      doc.setFont("helvetica", "bold");
      doc.text(`${team.points}`, margin + 160, standingsY + 5, { align: "center" });

      const nrrStr = team.nrr > 0 ? `+${team.nrr.toFixed(3)}` : team.nrr.toFixed(3);
      if (team.nrr > 0) doc.setTextColor(16, 124, 65);
      else if (team.nrr < 0) doc.setTextColor(165, 42, 42);
      else doc.setTextColor(100, 116, 139);
      doc.text(nrrStr, margin + 180, standingsY + 5, { align: "right" });

      standingsY += 7.5;
      drawHorizontalLine(standingsY, [226, 232, 240], 0.15);
    });

    standingsY += 5;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text("Note: NRR = (Runs Scored / Overs Faced) - (Runs Conceded / Overs Bowled).", margin + 2, standingsY);
    doc.text(
      "Teams dismissed before completing full allotted overs are considered to have faced their full quota of overs.",
      margin + 2,
      standingsY + 3.5
    );

    drawFooter(2);
  }

  // Save the PDF Match Report
  const filename = `PATHTHAWASL2026_MatchReport_${match.teamA.replace(/\s+/g, "")}_vs_${match.teamB.replace(/\s+/g, "")}.pdf`;
  doc.save(filename);
}