/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { jsPDF } from "jspdf";
import { Match, InningsState, BatsmanStats, BowlerStats, CommitteeMember } from "../types";
import { formatOvers, calculateStrikeRate, calculateEconomyRate, calculatePointsTable } from "../utils";

/**
 * Generates and downloads a beautifully styled PDF Match Report
 */
export function downloadMatchReportPDF(
  match: Match,
  allMatches: Match[] = [],
  committeeMembers: CommitteeMember[] = []
) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin; // 180mm
  const bpo = match.ballsPerOver || 6;

  // Helper to draw a horizontal line
  const drawHorizontalLine = (y: number, colorRGB = [226, 232, 240], thickness = 0.2) => {
    doc.setDrawColor(colorRGB[0], colorRGB[1], colorRGB[2]);
    doc.setLineWidth(thickness);
    doc.line(margin, y, margin + contentWidth, y);
  };

  // Helper to draw header banner
  const drawHeaderBanner = (pageNum: number) => {
    // Dark Emerald Header
    doc.setFillColor(7, 36, 16);
    doc.rect(0, 0, pageWidth, 35, "F");

    // Gold accent line
    doc.setFillColor(234, 179, 8);
    doc.rect(0, 34, pageWidth, 1, "F");

    // Logo / Text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("PATHTHAWA SUPER LEAGUE 2026", margin, 12);

    doc.setFontSize(16);
    doc.setTextColor(234, 179, 8);
    doc.text("OFFICIAL MATCH REPORT", margin, 20);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(167, 243, 208);
    doc.text("Generated by Ismath Admin Scoring Center", margin, 27);

    // Page Number on top right
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Page ${pageNum} of 2`, pageWidth - margin, 15, { align: "right" });
  };

  // Helper to draw footer
  const drawFooter = (pageNum: number) => {
    const y = pageHeight - 12;
    drawHorizontalLine(y - 3, [200, 220, 200], 0.3);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text("This is an official computer-generated Match Report from PATHTHAWA SUPER LEAGUE 2026 Live Scoring.", margin, y);
    doc.text(`Page ${pageNum}`, pageWidth - margin, y, { align: "right" });
  };

  // ================= PAGE 1 =================
  drawHeaderBanner(1);

  let currentY = 44;

  // Match Summary Card
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.rect(margin, currentY, contentWidth, 38, "FD");

  // Bold Match Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${match.teamA.toUpperCase()} vs ${match.teamB.toUpperCase()}`, margin + 5, currentY + 6);

  // Match Details
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Date: ${match.date}   |   Venue: ${match.venue}   |   Overs: Max ${match.maxOvers}`, margin + 5, currentY + 12);
  
  const tossText = match.tossWinner 
    ? `${match.tossWinner} won the toss and elected to ${match.tossDecision === "Bat" ? "Bat first" : "Bowl first"}`
    : "Toss details not recorded";
  doc.text(tossText, margin + 5, currentY + 17);

  // Result Banner
  doc.setFillColor(254, 243, 199);
  doc.rect(margin + 3, currentY + 21, contentWidth - 6, 12, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(146, 64, 14);
  const resultStr = match.resultMessage || "Match upcoming or in progress";
  doc.text(`RESULT: ${resultStr}`, margin + 8, currentY + 27);

  if (match.manOfTheMatch) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(`Man of the Match: `, margin + 8, currentY + 31);
    doc.setFont("helvetica", "bold");
    doc.text(match.manOfTheMatch, margin + 38, currentY + 31);
  }

  currentY += 46;

  // INNINGS 1 DETAILS
  const inn1 = match.innings1;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(4, 120, 87);
  doc.text(`1st Innings: ${inn1 ? inn1.battingTeam : match.teamA} Scorecard`, margin, currentY);

  if (inn1) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    const scoreStr = `${inn1.runs}/${inn1.wickets} (${formatOvers(inn1.balls, bpo)} Overs)`;
    doc.text(scoreStr, pageWidth - margin, currentY, { align: "right" });
    currentY += 4;

    // Batting Table
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, currentY, contentWidth, 6, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    
    // Headers
    doc.text("BATSMAN", margin + 3, currentY + 4);
    doc.text("OUT/STATUS", margin + 45, currentY + 4);
    doc.text("RUNS", margin + 115, currentY + 4, { align: "right" });
    doc.text("BALLS", margin + 130, currentY + 4, { align: "right" });
    doc.text("4s", margin + 143, currentY + 4, { align: "right" });
    doc.text("6s", margin + 155, currentY + 4, { align: "right" });
    doc.text("SR", margin + 175, currentY + 4, { align: "right" });

    currentY += 6;

    // Rows
    inn1.batsmen.forEach((batsman) => {
      if (currentY > pageHeight - 60) return; // avoid overflow (though page 1 has plenty space)
      
      doc.setFont("helvetica", batsman.isOut ? "normal" : "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      
      doc.text(batsman.name, margin + 3, currentY + 5);
      
      let statusStr = "Not Out";
      if (batsman.isOut) {
        statusStr = batsman.dismissalType || "Out";
        if (batsman.dismissedBy) {
          statusStr += ` b ${batsman.dismissedBy}`;
        }
      }
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(statusStr, margin + 45, currentY + 5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text(`${batsman.runs}`, margin + 115, currentY + 5, { align: "right" });
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(`${batsman.balls}`, margin + 130, currentY + 5, { align: "right" });
      doc.text(`${batsman.fours}`, margin + 143, currentY + 5, { align: "right" });
      doc.text(`${batsman.sixes}`, margin + 155, currentY + 5, { align: "right" });
      doc.text(calculateStrikeRate(batsman.runs, batsman.balls), margin + 175, currentY + 5, { align: "right" });
      
      currentY += 7;
      drawHorizontalLine(currentY, [241, 245, 249], 0.1);
    });

    // Extras & Totals
    currentY += 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    const extrasStr = `Extras: Wides ${inn1.wides || 0}, No Balls ${inn1.noBalls || 0}, Byes ${inn1.byes || 0}, Leg Byes ${inn1.legByes || 0}`;
    doc.text(extrasStr, margin + 3, currentY + 3);

    currentY += 8;

    // Bowlers Table Innings 1
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(4, 120, 87);
    doc.text("Bowling Card", margin, currentY);
    currentY += 4;

    doc.setFillColor(241, 245, 249);
    doc.rect(margin, currentY, contentWidth, 6, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    
    doc.text("BOWLER", margin + 3, currentY + 4);
    doc.text("OVERS", margin + 80, currentY + 4, { align: "right" });
    doc.text("MAIDENS", margin + 105, currentY + 4, { align: "right" });
    doc.text("RUNS", margin + 130, currentY + 4, { align: "right" });
    doc.text("WICKETS", margin + 155, currentY + 4, { align: "right" });
    doc.text("ECON", margin + 175, currentY + 4, { align: "right" });

    currentY += 6;

    inn1.bowlers.forEach((bowler) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      
      doc.text(bowler.name, margin + 3, currentY + 4);
      doc.text(formatOvers(bowler.ballsBowled, bpo), margin + 80, currentY + 4, { align: "right" });
      doc.text(`${bowler.maidens}`, margin + 105, currentY + 4, { align: "right" });
      doc.text(`${bowler.runsConceded}`, margin + 130, currentY + 4, { align: "right" });
      
      doc.setFont("helvetica", "bold");
      doc.text(`${bowler.wickets}`, margin + 155, currentY + 4, { align: "right" });
      
      doc.setFont("helvetica", "normal");
      doc.text(calculateEconomyRate(bowler.runsConceded, bowler.ballsBowled, bpo), margin + 175, currentY + 4, { align: "right" });
      
      currentY += 7;
      drawHorizontalLine(currentY, [241, 245, 249], 0.1);
    });
  } else {
    currentY += 10;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text("Innings 1 has not started yet.", margin + 10, currentY);
  }

  drawFooter(1);

  // ================= PAGE 2 =================
  doc.addPage();
  drawHeaderBanner(2);

  currentY = 44;

  // INNINGS 2 DETAILS
  const inn2 = match.innings2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(29, 78, 216); // Blue primary for 2nd innings
  doc.text(`2nd Innings: ${inn2 ? inn2.battingTeam : match.teamB} Scorecard`, margin, currentY);

  if (inn2) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    const scoreStr = `${inn2.runs}/${inn2.wickets} (${formatOvers(inn2.balls, bpo)} Overs)`;
    doc.text(scoreStr, pageWidth - margin, currentY, { align: "right" });
    currentY += 4;

    // Batting Table
    doc.setFillColor(239, 246, 255); // soft blue header
    doc.rect(margin, currentY, contentWidth, 6, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    
    // Headers
    doc.text("BATSMAN", margin + 3, currentY + 4);
    doc.text("OUT/STATUS", margin + 45, currentY + 4);
    doc.text("RUNS", margin + 115, currentY + 4, { align: "right" });
    doc.text("BALLS", margin + 130, currentY + 4, { align: "right" });
    doc.text("4s", margin + 143, currentY + 4, { align: "right" });
    doc.text("6s", margin + 155, currentY + 4, { align: "right" });
    doc.text("SR", margin + 175, currentY + 4, { align: "right" });

    currentY += 6;

    // Rows
    inn2.batsmen.forEach((batsman) => {
      doc.setFont("helvetica", batsman.isOut ? "normal" : "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      
      doc.text(batsman.name, margin + 3, currentY + 5);
      
      let statusStr = "Not Out";
      if (batsman.isOut) {
        statusStr = batsman.dismissalType || "Out";
        if (batsman.dismissedBy) {
          statusStr += ` b ${batsman.dismissedBy}`;
        }
      }
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(statusStr, margin + 45, currentY + 5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text(`${batsman.runs}`, margin + 115, currentY + 5, { align: "right" });
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(`${batsman.balls}`, margin + 130, currentY + 5, { align: "right" });
      doc.text(`${batsman.fours}`, margin + 143, currentY + 5, { align: "right" });
      doc.text(`${batsman.sixes}`, margin + 155, currentY + 5, { align: "right" });
      doc.text(calculateStrikeRate(batsman.runs, batsman.balls), margin + 175, currentY + 5, { align: "right" });
      
      currentY += 7;
      drawHorizontalLine(currentY, [239, 246, 255], 0.1);
    });

    // Extras & Totals
    currentY += 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    const extrasStr = `Extras: Wides ${inn2.wides || 0}, No Balls ${inn2.noBalls || 0}, Byes ${inn2.byes || 0}, Leg Byes ${inn2.legByes || 0}`;
    doc.text(extrasStr, margin + 3, currentY + 3);

    currentY += 8;

    // Bowlers Table Innings 2
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(29, 78, 216);
    doc.text("Bowling Card", margin, currentY);
    currentY += 4;

    doc.setFillColor(239, 246, 255);
    doc.rect(margin, currentY, contentWidth, 6, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    
    doc.text("BOWLER", margin + 3, currentY + 4);
    doc.text("OVERS", margin + 80, currentY + 4, { align: "right" });
    doc.text("MAIDENS", margin + 105, currentY + 4, { align: "right" });
    doc.text("RUNS", margin + 130, currentY + 4, { align: "right" });
    doc.text("WICKETS", margin + 155, currentY + 4, { align: "right" });
    doc.text("ECON", margin + 175, currentY + 4, { align: "right" });

    currentY += 6;

    inn2.bowlers.forEach((bowler) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      
      doc.text(bowler.name, margin + 3, currentY + 4);
      doc.text(formatOvers(bowler.ballsBowled, bpo), margin + 80, currentY + 4, { align: "right" });
      doc.text(`${bowler.maidens}`, margin + 105, currentY + 4, { align: "right" });
      doc.text(`${bowler.runsConceded}`, margin + 130, currentY + 4, { align: "right" });
      
      doc.setFont("helvetica", "bold");
      doc.text(`${bowler.wickets}`, margin + 155, currentY + 4, { align: "right" });
      
      doc.setFont("helvetica", "normal");
      doc.text(calculateEconomyRate(bowler.runsConceded, bowler.ballsBowled, bpo), margin + 175, currentY + 4, { align: "right" });
      
      currentY += 7;
      drawHorizontalLine(currentY, [239, 246, 255], 0.1);
    });

    currentY += 8;

    // Fall of Wickets Summary if available
    const allFows = [...(inn1?.fallOfWickets || []), ...(inn2?.fallOfWickets || [])];
    if (allFows.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text("Key Partnerships & Wickets Summary", margin, currentY);
      currentY += 4;
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const fowSummary1 = inn1?.fallOfWickets.length 
        ? `${inn1.battingTeam} Wickets: ` + inn1.fallOfWickets.map(f => `${f.wicketNumber}-${f.score} (${f.batsmanName})`).join(", ")
        : "";
      const fowSummary2 = inn2?.fallOfWickets.length 
        ? `${inn2.battingTeam} Wickets: ` + inn2.fallOfWickets.map(f => `${f.wicketNumber}-${f.score} (${f.batsmanName})`).join(", ")
        : "";

      if (fowSummary1) {
        doc.text(doc.splitTextToSize(fowSummary1, contentWidth), margin, currentY);
        currentY += inn1.fallOfWickets.length > 3 ? 10 : 6;
      }
      if (fowSummary2) {
        doc.text(doc.splitTextToSize(fowSummary2, contentWidth), margin, currentY);
      }
    }

  } else {
    currentY += 10;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text("Innings 2 has not started yet or match was decided in 1st innings.", margin + 10, currentY);
  }

  const sigY = pageHeight - 38;

  // Draw Captains Section
  const captainsY = sigY - 24; // 24mm above signatures
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.2);
  doc.line(margin, captainsY, margin + contentWidth, captainsY);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("TEAM CAPTAINS", margin, captainsY + 4.5);

  const drawCaptainPlaceholder = (x: number, y: number, w: number, h: number, nameStr: string) => {
    // Draw colored box
    doc.setFillColor(30, 64, 175); // Royal Blue
    doc.roundedRect(x, y, w, h, 2, 2, "F");
    
    // Draw captain initial
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    const initial = nameStr.trim().charAt(0).toUpperCase() || "C";
    doc.text(initial, x + w / 2, y + h / 2 + 3.5, { align: "center" });
  };

  // Find Team A Captain
  const teamACard = committeeMembers.find(m => 
    m.isOwner === true && 
    (m.role.toLowerCase().includes(match.teamA.toLowerCase()) || 
     match.teamA.toLowerCase().includes(m.role.replace(/^Owner,\s*/i, "").toLowerCase()))
  );
  
  // Find Team B Captain
  const teamBCard = committeeMembers.find(m => 
    m.isOwner === true && 
    (m.role.toLowerCase().includes(match.teamB.toLowerCase()) || 
     match.teamB.toLowerCase().includes(m.role.replace(/^Owner,\s*/i, "").toLowerCase()))
  );

  // Draw Team A Captain on the left
  const capAName = teamACard?.captainName || "Not Assigned";
  const capAPhoto = teamACard?.captainPhotoUrl;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${match.teamA} Captain:`, margin + 5, captainsY + 11);
  doc.setFont("helvetica", "normal");
  doc.text(capAName, margin + 5, captainsY + 15);
  
  // Render Team A Captain photo
  const photoSize = 12; // 12mm
  const photoAX = margin + 50;
  const photoAY = captainsY + 7;
  if (capAPhoto && capAPhoto.startsWith("data:image/") && capAPhoto.includes(";base64,")) {
    try {
      const format = capAPhoto.split(";")[0].split("/")[1].split("+")[0].toUpperCase();
      doc.addImage(capAPhoto, format === "JPEG" ? "JPEG" : "PNG", photoAX, photoAY, photoSize, photoSize);
    } catch (e) {
      console.error(e);
      drawCaptainPlaceholder(photoAX, photoAY, photoSize, photoSize, capAName);
    }
  } else {
    drawCaptainPlaceholder(photoAX, photoAY, photoSize, photoSize, capAName);
  }

  // Draw Team B Captain on the right
  const capBName = teamBCard?.captainName || "Not Assigned";
  const capBPhoto = teamBCard?.captainPhotoUrl;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`${match.teamB} Captain:`, margin + 100, captainsY + 11);
  doc.setFont("helvetica", "normal");
  doc.text(capBName, margin + 100, captainsY + 15);

  // Render Team B Captain photo
  const photoBX = margin + 145;
  const photoBY = captainsY + 7;
  if (capBPhoto && capBPhoto.startsWith("data:image/") && capBPhoto.includes(";base64,")) {
    try {
      const format = capBPhoto.split(";")[0].split("/")[1].split("+")[0].toUpperCase();
      doc.addImage(capBPhoto, format === "JPEG" ? "JPEG" : "PNG", photoBX, photoBY, photoSize, photoSize);
    } catch (e) {
      console.error(e);
      drawCaptainPlaceholder(photoBX, photoBY, photoSize, photoSize, capBName);
    }
  } else {
    drawCaptainPlaceholder(photoBX, photoBY, photoSize, photoSize, capBName);
  }

  // Add signature section at the bottom of Page 2
  doc.setDrawColor(220, 220, 220);
  doc.line(margin + 5, sigY, margin + 55, sigY);
  doc.line(pageWidth - margin - 55, sigY, pageWidth - margin - 5, sigY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("Authorized Tournament Scorer", margin + 30, sigY + 4, { align: "center" });
  doc.text("Chief Tournament Director", pageWidth - margin - 30, sigY + 4, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(7, 36, 16);
  doc.text("ISMATH", margin + 30, sigY - 2, { align: "center" });
  doc.text("ISMAN SCORING PANEL", pageWidth - margin - 30, sigY - 2, { align: "center" });

  drawFooter(2);

  // ================= PAGE 3 (TOURNAMENT STANDINGS & NET RUN RATES) =================
  if (allMatches && allMatches.length > 0) {
    doc.addPage();
    drawHeaderBanner(3);

    let standingsY = 44;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(7, 36, 16); // Dark emerald theme primary
    doc.text("Tournament Standings & Net Run Rates (NRR)", margin, standingsY);
    standingsY += 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text("Latest updated standings including Net Run Rate (NRR) for all matches.", margin, standingsY + 2);
    standingsY += 8;

    // Table Header
    doc.setFillColor(7, 36, 16);
    doc.rect(margin, standingsY, contentWidth, 7, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(255, 255, 255);

    doc.text("POS", margin + 5, standingsY + 4.8, { align: "center" });
    doc.text("TEAM", margin + 10, standingsY + 4.8);
    doc.text("P", margin + 65, standingsY + 4.8, { align: "center" });
    doc.text("W", margin + 73, standingsY + 4.8, { align: "center" });
    doc.text("L", margin + 81, standingsY + 4.8, { align: "center" });
    doc.text("T/D", margin + 89, standingsY + 4.8, { align: "center" });
    doc.text("FOR (Runs/Overs)", margin + 112, standingsY + 4.8, { align: "center" });
    doc.text("AGAINST (Runs/Overs)", margin + 140, standingsY + 4.8, { align: "center" });
    doc.text("PTS", margin + 160, standingsY + 4.8, { align: "center" });
    doc.text("NET RUN RATE (NRR)", margin + 180, standingsY + 4.8, { align: "right" });

    standingsY += 7;

    const pointsTable = calculatePointsTable(allMatches);

    pointsTable.forEach((team, idx) => {
      // Alternating rows
      if (idx % 2 === 0) {
        doc.setFillColor(248, 250, 252);
      } else {
        doc.setFillColor(241, 245, 249);
      }
      doc.rect(margin, standingsY, contentWidth, 8, "F");

      // Text colors
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      
      // Highlight current match teams
      const isCurrentTeam = team.teamName === match.teamA || team.teamName === match.teamB;
      if (isCurrentTeam) {
        doc.setTextColor(4, 120, 87); // bold emerald for current team
      } else {
        doc.setTextColor(15, 23, 42);
      }

      doc.text(`${idx + 1}`, margin + 5, standingsY + 5.2, { align: "center" });
      doc.text(team.teamName, margin + 10, standingsY + 5.2);

      doc.setFont("helvetica", "normal");
      doc.text(`${team.played}`, margin + 65, standingsY + 5.2, { align: "center" });
      doc.text(`${team.won}`, margin + 73, standingsY + 5.2, { align: "center" });
      doc.text(`${team.lost}`, margin + 81, standingsY + 5.2, { align: "center" });
      doc.text(`${team.tied}`, margin + 89, standingsY + 5.2, { align: "center" });

      const forStr = `${team.runsScored}/${team.wicketsLost ?? 0} (${team.oversFaced.toFixed(1)})`;
      const agnstStr = `${team.runsConceded}/${team.wicketsTaken ?? 0} (${team.oversBowled.toFixed(1)})`;
      doc.text(forStr, margin + 112, standingsY + 5.2, { align: "center" });
      doc.text(agnstStr, margin + 140, standingsY + 5.2, { align: "center" });

      doc.setFont("helvetica", "bold");
      doc.text(`${team.points}`, margin + 160, standingsY + 5.2, { align: "center" });

      // Color-code the NRR
      const nrrStr = team.nrr > 0 ? `+${team.nrr.toFixed(3)}` : team.nrr.toFixed(3);
      if (team.nrr > 0) {
        doc.setTextColor(16, 124, 65); // Green for positive NRR
      } else if (team.nrr < 0) {
        doc.setTextColor(165, 42, 42); // Brownish red for negative NRR
      } else {
        doc.setTextColor(100, 116, 139); // Gray for zero NRR
      }
      doc.text(nrrStr, margin + 180, standingsY + 5.2, { align: "right" });

      standingsY += 8;
      drawHorizontalLine(standingsY, [226, 232, 240], 0.15);
    });

    // Add note about NRR calculation rules
    standingsY += 6;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text("Note: NRR = (Runs Scored / Overs Faced) - (Runs Conceded / Overs Bowled).", margin + 3, standingsY);
    doc.text("Teams dismissed before completing full allotted overs are considered to have faced their full quota of overs.", margin + 3, standingsY + 3.5);

    drawFooter(3);
  }

  // Save the PDF Match Report
  const filename = `PATHTHAWASL2026_MatchReport_${match.teamA.replace(/\s+/g, "")}_vs_${match.teamB.replace(/\s+/g, "")}.pdf`;
  doc.save(filename);
}
